[server]
enableWebsocketCompression = false
enableCORS = false
enableXsrfProtection = false
# ADD THESE TWO LINES:
headless = true
address = "0.0.0.0"

[browser]
# This forces the browser to not 'gather' usage stats, 
# which DuckDuckGo and Safari often flag as trackers.
gatherUsageStats = false
